#!/usr/bin/env python3
"""Generate the derived pages: rules/changes.md (every errata and ruling annotation, by file,
plus the rulings register), rules/coverage.md (SPI case coverage by section) and
rulings/register.md (browsable list of every ruling and variant).

  python3 tools/gen_pages.py [repo_root]     # rewrites the pages; prints which changed

tests/test_gen_pages.py fails when the committed pages are stale, so run this after editing
any ::: errata / ::: ruling / ::: variant / ::: spi badge or a rulings/R-nnn.md / V-nnn.md.
"""
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import check_coverage as cc  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
ANNOT = re.compile(r"^\s{0,3}:::\s+(errata|ruling|variant)\s+(\S+)(?:\s+(?:—|--)\s+(.*?))?\s*$")
KINDS = {"errata": "errata", "ruling": "rulings", "variant": "variants"}
GENERATED = {"changes.md", "coverage.md"}
HEADER = "<!-- generated by tools/gen_pages.py; do not edit -->"


def _title(md: str, fallback: str) -> str:
    m = re.search(r"^title:\s*(.+?)\s*$", md, re.M)
    return m.group(1) if m else fallback


def _rules_files(rules_dir: pathlib.Path) -> list[pathlib.Path]:
    return sorted(p for p in rules_dir.glob("*.md") if p.name not in GENERATED)


def collect_annotations(rules_dir: pathlib.Path) -> dict[str, dict]:
    out: dict[str, dict] = {}
    for p in _rules_files(rules_dir):
        md = p.read_text()
        entry = {"title": _title(md, p.stem), "errata": [], "rulings": [], "variants": []}
        for line in md.splitlines():
            m = ANNOT.match(line)
            if m:
                entry[KINDS[m.group(1)]].append((m.group(2), m.group(3) or ""))
        out[f"rules/{p.name}"] = entry
    return out


def _rulings(root: pathlib.Path, prefix: str = "R") -> list[dict]:
    out = []
    for p in sorted((root / "rulings").glob(f"{prefix}-*.md")):
        md = p.read_text()
        fm = {}
        for key in ("id", "status", "affects"):
            m = re.search(rf"^{key}:\s*(.+?)\s*$", md, re.M)
            fm[key] = m.group(1) if m else ""
        fm["affects"] = ", ".join(x.strip() for x in fm["affects"].strip("[]").split(",") if x.strip())
        fm["file"] = p.name
        m = re.search(r"^#\s+\S+\s+—\s+(.+?)\s*$", md, re.M)
        fm["title"] = m.group(1) if m else ""
        out.append(fm)
    return out


def render_changes(root: pathlib.Path) -> str:
    ann = collect_annotations(root / "rules")
    lines = ["---", "title: Changes from the original", "---", "", HEADER,
             "# Changes from the original", "",
             "Every place the restated rules differ from the 1979 text as printed: SPI's",
             "September 1979 errata (`E-nnn`, indexed in `data/errata/INDEX.md`) and our",
             "own rulings (`R-nnn`, in `rulings/`), plus community variants we record but",
             "do not adopt (`V-nnn`, also in `rulings/`). Generated from the `::: errata`,",
             "`::: ruling` and `::: variant` annotations in the rules files.", ""]
    for path, e in ann.items():
        if not e["errata"] and not e["rulings"] and not e["variants"]:
            continue
        lines += [f"## [{e['title']}](./{path.split('/', 1)[1]})", ""]
        for eid, text in e["errata"]:
            lines.append(f"- **{eid}**" + (f" — {text}" if text else ""))
        for rid, text in e["rulings"] + e["variants"]:
            lines.append(f"- [{rid}](../rulings/{rid}.md)" + (f" — {text}" if text else ""))
        lines.append("")
    rulings = _rulings(root)
    lines += ["## Rulings register", ""]
    if rulings:
        lines += ["| Id | Status | Affects |", "|---|---|---|"]
        lines += [f"| [{r['id']}](../rulings/{r['file']}) | {r['status']} | {r['affects']} |" for r in rulings]
    else:
        lines.append("No rulings yet.")
    variants = _rulings(root, "V")
    if variants:
        lines += ["", "## Variants register", "", "| Id | Status | Affects |", "|---|---|---|"]
        lines += [f"| [{v['id']}](../rulings/{v['file']}) | {v['status']} | {v['affects']} |" for v in variants]
    lines.append("")
    return "\n".join(lines)


def render_coverage(root: pathlib.Path) -> str:
    cases = json.loads((root / "data" / "spi-cases.json").read_text())["cases"]
    ids = [c["id"] for c in cases]
    rules_dir = root / "rules"
    badges = {}
    titles = {}
    for p in _rules_files(rules_dir):
        md = p.read_text()
        badges[p.name] = cc.parse_badges(md)
        titles[p.name] = _title(md, p.stem)
    sections = sorted({c["section"] for c in cases})
    lines = ["---", "title: Coverage", "---", "", HEADER, "# SPI case coverage", "",
             "For each SPI section: how many cases are restated (a primary `::: spi` badge),",
             "omitted with a stated reason, or not yet covered, and which file restates it.",
             "Generated by `tools/gen_pages.py` from the badges in the rules files.", "",
             "| § | File | Restated | Omitted | Uncovered | Covered |", "|---|---|---|---|---|---|"]
    uncovered_all: list[str] = []
    for s in sections:
        rep = cc.coverage(ids, badges, sections={s})
        files = sorted({f for f, bs in badges.items() for b in bs if b["kind"] == "spi"
                        for c in b["cases"] if c.split(".")[0] == str(s)})
        links = ", ".join(f"[{titles[f]}](./{f})" for f in files) or "—"
        covered = rep["primary"] + rep["omitted"]
        pct = f"{round(100 * covered / rep['total'])} %" if rep["total"] else "—"
        lines.append(f"| {s} | {links} | {rep['primary']} | {rep['omitted']} | {len(rep['uncovered'])} | {pct} |")
        uncovered_all += rep["uncovered"]
    lines.append("")
    if uncovered_all:
        lines += [f"## {len(uncovered_all)} cases not yet covered", "", " ".join(f"`{c}`" for c in uncovered_all), ""]
    return "\n".join(lines)


def render_register(root: pathlib.Path) -> str:
    lines = ["---", "title: Register", "---", "", HEADER, "# Rulings register", "",
             "Every ruling (`R-nnn`) and recorded variant (`V-nnn`) in `rulings/`, with its",
             "status and the SPI cases it touches. Generated by `tools/gen_pages.py` from the",
             "files' frontmatter; how rulings work is in the [README](./README.md).", "",
             "## Rulings", ""]
    rulings = _rulings(root)
    if rulings:
        lines += ["| Id | Title | Status | Affects |", "|---|---|---|---|"]
        lines += [f"| [{r['id']}](./{r['file']}) | {r['title']} | {r['status']} | {r['affects']} |" for r in rulings]
    else:
        lines.append("No rulings yet.")
    variants = _rulings(root, "V")
    lines += ["", "## Variants", ""]
    if variants:
        lines += ["| Id | Title | Status | Affects |", "|---|---|---|---|"]
        lines += [f"| [{v['id']}](./{v['file']}) | {v['title']} | {v['status']} | {v['affects']} |" for v in variants]
    else:
        lines.append("No variants recorded.")
    lines.append("")
    return "\n".join(lines)


def write_pages(root: pathlib.Path) -> bool:
    changed = False
    for rel, text in (("rules/changes.md", render_changes(root)), ("rules/coverage.md", render_coverage(root)),
                      ("rulings/register.md", render_register(root))):
        p = root / rel
        if not p.exists() or p.read_text() != text:
            p.write_text(text)
            print(f"wrote {rel}")
            changed = True
    return changed


if __name__ == "__main__":
    write_pages(pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT)
