"""Generate data/map/seams.json: the hexes that touch across each sheet edge.

Sheets A-E lie west to east and abut with no shared column: column 33 of one
sheet meets column 01 of the next, row numbers continuing straight across
(cross-checked against the VASSAL board geometry, EXTRACTION.md). So the
next sheet's column 01 sits where column 34 would be, and the per-sheet
stagger rule of tools/map_geom.py says which rows touch. Features come from
the two edge records in data/map/hexsides.json (`HEX|SIDE`).

  python3 tools/map_seams.py          # rewrite data/map/seams.json
  python3 tools/map_seams.py --check  # exit 1 if the file is stale
"""
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from map_geom import parse_hex_id, row_shifted_east  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
MAP = ROOT / "data" / "map"
SEAMS = [("A", "B"), ("B", "C"), ("C", "D"), ("D", "E")]
OPPOSITE = {"E": "W", "NE": "SW", "SE": "NW"}


def build() -> dict:
    sheets = json.loads((MAP / "sheets.json").read_text())["sheets"]
    hexes = {h["id"] for h in json.loads((MAP / "hexes.json").read_text())["hexes"]}
    edge = {r["key"]: r for r in json.loads((MAP / "hexsides.json").read_text())["hexsides"] if r["b"] is None}
    seams = []
    for west, east in SEAMS:
        last = sheets[west]["cols"][1]
        pairs = []
        for hid in sorted(h for h in hexes if h[0] == west and parse_hex_id(h)[2] == last):
            _, r, _ = parse_hex_id(hid)
            # diagonal neighbours reach column last+1 only from a row not shifted west
            touching = [("E", r)]
            if row_shifted_east(r, sheets[west]):
                touching += [("NE", r + 1), ("SE", r - 1)]
            for side, er in touching:
                other = f"{east}{er:02d}01"
                if other not in hexes:
                    continue
                wa, eb = edge.get(f"{hid}|{side}"), edge.get(f"{other}|{OPPOSITE[side]}")
                fw, fe = set(wa["features"]) if wa else set(), set(eb["features"]) if eb else set()
                rec = {"west": hid, "west_side": side, "east": other, "east_side": OPPOSITE[side],
                       "features": sorted(fw | fe)}
                if fw ^ fe:
                    rec["one_side_only"] = sorted(fw ^ fe)
                pairs.append(rec)
        seams.append({"west": west, "east": east, "pairs": pairs})
    return {
        "sources": ["CNA1979:8.37", "vassal:CNAv2.1.0"],
        "notes": [
            "Generated by tools/map_seams.py from sheets.json, hexes.json and hexsides.json; do not edit by hand.",
            "Sheets abut: column 33 of each sheet meets column 01 of the next, same row numbers (a row not shifted west also touches rows r+1 and r-1 of the next sheet). Checked against the VASSAL board geometry: all pairs agree. Map E's column 00 is a strip of half hexes duplicating map D's column 33 and is not a hex.",
            "features is the union of the two sheets' edge records. one_side_only lists any feature drawn up to the edge on one sheet but not the other (seven tracks and one road); they are kept, as the map art cut at a sheet edge is the likelier error than a route that stops dead there.",
            "Slope and escarpment edges keep up unknown: the edge records do not say which side is higher. The engine should treat them as the hexside feature in both directions until up is read from the map.",
        ],
        "seams": seams,
    }


def main(argv):
    out = json.dumps(build(), indent=1, ensure_ascii=False) + "\n"
    path = MAP / "seams.json"
    if "--check" in argv:
        sys.exit(0 if path.exists() and path.read_text() == out else 1)
    path.write_text(out)


if __name__ == "__main__":
    main(sys.argv[1:])
